### ISSUE TITLE
I get this when setting the fan speed

### ISSUE THREAD

**Issue by awesome14** [devxpy/thinkfan-control-gui#3]
set level to 'full-speed'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "./fan.py", line 58, in <lambda>
    tk.Button(row2, text="Full", command=lambda: set_speed("full-speed")).grid(
  File "./fan.py", line 32, in set_speed
    encoding="utf-8",
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'encoding'

my command is: sudo python3 ./fan.py

**Comment by devxpy** [comment]
Should be fixed in https://github.com/devxpy/thinkfan-control-gui/commit/a203d4608e8b0fa1d10e66fb13cbfd20d64f14e8

**Comment by awesome14** [comment]
The problem is fixed. Thank you.
